let FirstName;
    console.log(FirstName);
let Age;
    console.log(Age);
let PhoneNumber;
    console.log(PhoneNumber);
var EmailAddress;
    console.log(EmailAddress);
var MailingAddress;
    console.log(MailingAddress);
let Program;
    console.log(Program);
var IDnumber;
    console.log(IDnumber);
var YearLevel;
    console.log(YearLevel);
var Section;
    console.log(Section);